// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int bigger = 0;
		int smaller = 0;
		int times = Integer.parseInt(args[0]);
		for (int i=0; i<times; i++) {
			if (Math.random() < 0.5){
				smaller++;
			}
			else {
				bigger++;
			}
		}
		double ratio = (double)smaller/(double)bigger;
		System.out.println("> 0.5: " + bigger);
		System.out.println("<= 0.5: " + smaller);
		System.out.println("Ratio: " + ratio);

	}
}
